### ISSUE TITLE
Regarding the patches used for training the segmentation network

### ISSUE THREAD

**Issue by ghost** [jhacsonmeza/MarkerPose#1]
Hello,
Thanks for the amazing work! 
In your paper, you state: "For EllipSegNet training, we extract 120  120 patches from some of the images used for training the SuperPoinlike network, resulting in 11010 patches".
Is this DB available? If not how can I create it? 
I am only interested in training EllipSegNet. 

```
imlist = sorted(glob.glob(os.path.join(root,'patch120','*')))
masklist = sorted(glob.glob(os.path.join(root,'mask120','*')))

```

Thanks.

**Comment by jhacsonmeza** [comment]
Thank you!
My apologies for the delayed response. [Here](https://drive.google.com/drive/folders/1kKPhAadalEUiYc6GkqAgqEXl258B1ojd?usp=sharing) you can download the dataset. You can move `patch120/` and `mask120/` to the `dataset/` folder (the folder with the pose estimation examples and models weights). Then, modify the `root` variable from `train_ellipsegnet.py`:
```
root = os.path.abspath('../dataset')
```
With that, you can be able to train EllipSegNet. Let us know if you have any question!
