### ISSUE TITLE
video stream support

### ISSUE THREAD

**Issue by shadowver** [jhacsonmeza/MarkerPose#4]
Thanks for the opening the wonderful code. Does this library support live video stream? I have rewrote the code for a stereo webcam (640 * 480) instead a  dataset, however, the code return a segmentation fault.

**Comment by jhacsonmeza** [comment]
If you're acquiring frames in real-time, you just need to change the part where the images are loaded locally from the folder and you have to ensure you're passing [here](https://github.com/jhacsonmeza/MarkerPose/blob/main/C%2B%2B/robot_test.cpp#L54-L55) the loaded frames from your stereo cameras. That segmentation fault makes me think that the arrays you're passing to `markerpose` function is probably empty or not properly formatted. I don't know what you're using to acquire the stereo images, but if you're still having problems, I don't know if you mind to share your code to see if I can help.

**Comment by shadowver** [comment]
Not at all. The following is the code that I wrote to use libuvc transmit and opencv to wrap the image data: 
        uvc_frame_t* frame;
        uvc_frame_t* rframe;

        int res = uvc_stream_get_frame(strmh, &frame, 0);
        res = uvc_stream_get_frame(strmh1, &rframe, 0);
                
        uvc_frame_t *bgr;
        uvc_frame_t *bgr1;
        bgr = uvc_allocate_frame(frame->height * frame->width);// for grayscale left camera
        bgr1 = uvc_allocate_frame(rframe->height * rframe->width);// for grayscale right camera

        uvc_mjpeg2gray(frame, bgr);
        uvc_mjpeg2gray(rframe, bgr1);

        cv::Mat leftImg = cv::Mat(frame->height, frame->width, CV_8U, (unsigned char*)bgr->data);       // cv_8uc1, grayscale
        cv::Mat rightImg = cv::Mat(rframe->height, rframe->width, CV_8U, (unsigned char*)bgr1->data); 

        if(!leftImg.empty() && !rightImg.empty())
            // Pose estimation
            auto [R, t] = markerpose(leftImg, rightImg);

I have backtraced the coredump. It appeared that when the input images do not contain the marker info, the keypoint within sortedPoints function does contain any information which leads to error to int* pkp = kp.data_ptr<int>(); Thanks for the help.

p.s. the image transmitting is fine when I comment out makerpose(leftimg, leftImg) function for testing.

**Comment by jhacsonmeza** [comment]
Oh, I see! If I'm not wrong we didn't consider the case where `sortedPoints` returned nothing when we don't have any marker in the scene. The correct approach must be to test if the function is actually returning anything to skip the rest of the code and avoid errors, but the current version of the released implementation lacks that. 
Can you try this inside the `sortedPoints` just before returning (exactly before this [line](https://github.com/jhacsonmeza/MarkerPose/blob/main/C%2B%2B/src/utils/markerpose_utils.cpp#L81)):
```
if (kp.numel() == 0) std::cout<<"The kp array is empty\n";
```
In this way I think we can actually know that the tensor is empty.

**Comment by shadowver** [comment]
The line you referred is the "return kp;" . Wont it be reasonable to call the test line(if (kp.numel() == 0) before  int* pkp = kp.data_ptr()? As if kp is an empty array calling pkp from data_ptr<int>() will cause error. I am thinking adjust the code with returning tensor.zeros() for keypoints and  cv::Mat::zeros(3, 3, CV_32F) and cv::Mat::zeros(3, 1, CV_32F) for R and t for the non-marker scene. Any suggestions?

**Comment by jhacsonmeza** [comment]
It's equivalent, at the end of the day what I wanted to do is to test if with the line `if (kp.numel() == 0) std::cout<<"The kp array is empty\n";` we're actually able to identify your failing case. And the array `kp` is created and returned by `sortedPoints`. That's why I said to add the line there, but for the test (and just for the test) it doesn't matter if you do it there or inside `MarkerPoseImpl::pixelPoints` or in `MarkerPoseImpl::forward`. 

So, the point is, if we can confirm that `if (kp.numel() == 0)` can be used to detect the failing case (I'm not sure), then you should use:
```C++
if (kp1.numel() == 0 || kp2.numel() == 0) {
    cv::Mat R, t;
    return {R, t};
}
```
just before the line `int* pkp1 = kp1.data_ptr<int>();`.

Then inside your image acquisition loop (where you use the `markerpose` fucntion) you can do:
```C++
if(!leftImg.empty() && !rightImg.empty()) {
    // Pose estimation
    auto [R, t] = markerpose(leftImg, rightImg);

    // If empty, ignore drawing axes for these frames
    if (R.empty() || t.empty()) continue;
    ...
}
```
Let me know if this works.

**Comment by shadowver** [comment]
I did test the code if(kp.numel() == 0)  before int* pkp = kp.data_ptr<int>() as it was this line produced the error with various dataset. The result revealed that kp is empty if there is no pre-trained marker inside the scene. The live stream mode is up and running.  However, when in the live stream mode, the program crashes and produces a segmentation fault when a marker appears in the scene. I will keep dig the reason behind it.

**Comment by jhacsonmeza** [comment]
But did you try the two changes I suggested in my last comment?

**Comment by shadowver** [comment]
I did try the two suggestions you mentioned in the last comment. It does work in the live stream mode when there is no marker appears in the scene. kp.numel() returns 0, and R, t return  empty which is what we expected.  However, the program will crash after a short period of time and produces the following error:
"terminate called after throwing an instance of 'c10::IndexError'
  what():  index 1 is out of bounds for dimension 0 with size 1
Exception raised from get at ../aten/src/ATen/native/cpu/IndexKernelUtils.h:44 (most recent call first):"

**Comment by jhacsonmeza** [comment]
Ok. That's interesting. Could you check if that error is inside `sortedPoints`? I'm thinking it might be there because we use the `index` function multiple times there. Probably the array becomes empty at the beginning of the function before returning.

**Comment by shadowver** [comment]
Sounds like it. I will keep digging. It is a difference issue then. I will close this one now and reopen a new one once I have a solution. Thanks a lot for all the instructions.
